# Generated by Django 5.2.11 on 2026-03-04 19:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0007_alter_contact_associated_contacts'),
        ('core', '0029_document_sequence'),
        ('inventory', '0016_add_qty_purchased_to_purchase_list_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.CharField(blank=True, help_text='Auto-gerado ao gravar (ex: SO/2026/00001).', max_length=32, unique=True, verbose_name='Nº Venda')),
                ('document_type', models.CharField(choices=[('quotation', 'Orçamento'), ('order', 'Encomenda'), ('invoice', 'Fatura')], default='order', max_length=16, verbose_name='Tipo de Documento')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('delivered', 'Entregue'), ('invoiced', 'Faturado'), ('cancelled', 'Cancelado')], default='draft', max_length=16, verbose_name='Estado')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Não Pago'), ('partial', 'Parcial'), ('paid', 'Pago')], default='unpaid', max_length=16, verbose_name='Estado Pagamento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal (s/ IVA)')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total (c/ IVA)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='contacts.contact', verbose_name='Cliente')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL = global (visível para todas as empresas).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_orders', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Preço Unitário')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='IVA (%)')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_order_lines', to='inventory.product', verbose_name='Produto')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saleorder', verbose_name='Venda')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_order_lines', to='inventory.uom', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Linha de Venda',
                'verbose_name_plural': 'Linhas de Venda',
                'ordering': ['created_at'],
            },
        ),
    ]
