# Generated by Django 5.2.11 on 2026-03-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='document_type',
            field=models.CharField(choices=[('quotation', 'Orçamento'), ('order', 'Encomenda'), ('invoice', 'Fatura')], default='quotation', max_length=16, verbose_name='Tipo de Documento'),
        ),
    ]
