# Generated by Django 5.2.11 on 2026-03-04 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_document_sequence'),
        ('sales', '0002_auto_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Ex: Pronto pagamento, 30 dias, 30/60 dias', max_length=100, verbose_name='Nome')),
                ('days', models.PositiveIntegerField(default=0, help_text='Número de dias para pagamento (0 = pronto pagamento)', verbose_name='Dias')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_default', models.BooleanField(default=False, help_text='Seleccionada automaticamente em novas vendas.', verbose_name='Padrão')),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_payment_terms', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Condição de Pagamento (Venda)',
                'verbose_name_plural': 'Condições de Pagamento (Vendas)',
                'ordering': ['-is_default', 'days', 'name'],
            },
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to='sales.paymentterm', verbose_name='Condição de Pagamento'),
        ),
    ]
