# Generated by Django 5.2.11 on 2026-03-05 00:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_add_discount_pct_to_order_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='global_discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto aplicado ao subtotal total antes do IVA.', max_digits=5, verbose_name='Desconto Global (%)'),
        ),
    ]
