# Generated by Django 5.2.11 on 2026-03-05 23:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_global_discount_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor pago antecipadamente (sinal/adiantamento).', max_digits=14, verbose_name='Valor Pago'),
        ),
    ]
