# Generated by Django 5.2.11 on 2026-03-06 17:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_saleorder_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='signature_image',
            field=models.TextField(blank=True, default='', help_text='Base64 PNG do canvas de assinatura.', verbose_name='Imagem da Assinatura'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='signature_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('signed', 'Assinado'), ('refused', 'Recusado')], default='pending', max_length=16, verbose_name='Estado de Assinatura'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='signature_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token único para o link público de assinatura. Gerado ao enviar email.', max_length=64, null=True, unique=True, verbose_name='Token de Assinatura'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Assinatura'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='signed_by_name',
            field=models.CharField(blank=True, default='', help_text='Nome confirmado pelo cliente ao assinar.', max_length=200, verbose_name='Assinado Por'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Token'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valor pago antecipadamente (sinal/adiantamento).', max_digits=14, verbose_name='Valor Pago'),
        ),
    ]
