# Generated by Django 5.0.14 on 2026-02-08 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='core.company', verbose_name='Default Company'),
        ),
    ]
