# Generated by Django 5.2.11 on 2026-02-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_companies_customuser_default_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_app_password',
            field=models.TextField(blank=True, help_text='App Password gerada na conta Google/Microsoft. Armazenada de forma encriptada.', verbose_name='App Password (encriptada)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_provider',
            field=models.CharField(blank=True, choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Microsoft 365')], default='gmail', max_length=10, verbose_name='Provedor SMTP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_smtp_address',
            field=models.EmailField(blank=True, help_text='Endereço de email utilizado para enviar mensagens aos clientes.', max_length=254, verbose_name='Email para envio (SMTP)'),
        ),
    ]
