# Generated by Django 5.2.11 on 2026-02-19 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_smtp_email_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_app_password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_provider',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_smtp_address',
        ),
        migrations.CreateModel(
            name='UserEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Endereço de email utilizado para enviar mensagens. Ex: joao@gmail.com', max_length=254, verbose_name='Email de envio (SMTP)')),
                ('app_password', models.TextField(help_text='App Password gerada na conta Google/Microsoft. Nunca é a password principal — é uma password específica para aplicações. Armazenada de forma encriptada.', verbose_name='App Password (encriptada)')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Microsoft 365')], default='gmail', max_length=10, verbose_name='Provedor SMTP')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, o envio de emails fica suspenso para este utilizador.', verbose_name='Ativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Configuração de Email',
                'verbose_name_plural': 'Configurações de Email',
            },
        ),
    ]
