# Generated by Django 5.2.11 on 2026-02-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_email_app_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(blank=True, help_text='Imagem do avatar em formato base64 (data URL)', null=True),
        ),
    ]
