# Generated by Django 5.2.11 on 2026-02-21 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_avatar_base64'),
        ('core', '0016_chattermessage_bcc_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50, verbose_name='Aplicação')),
                ('level', models.CharField(choices=[('readonly', 'Read Only'), ('user', 'Utilizador'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=20, verbose_name='Nível')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_app_roles', to='core.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Permissão de Aplicação',
                'verbose_name_plural': 'Permissões de Aplicação',
                'ordering': ['user', 'company', 'app'],
                'unique_together': {('user', 'app', 'company')},
            },
        ),
    ]
