# Generated by Django 5.2.11 on 2026-02-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_approle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='Whether 2FA is active for this user'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, default='', help_text='Base32 secret for TOTP 2FA', max_length=64),
        ),
    ]
