# Generated by Django 5.0.14 on 2026-02-05 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF/Tax ID')),
                ('notes', models.TextField(blank=True)),
                ('contact_type', models.CharField(choices=[('CLIENT', 'Client'), ('SUPPLIER', 'Supplier'), ('BOTH', 'Both')], default='CLIENT', max_length=10)),
                ('contact_category', models.CharField(choices=[('PERSON', 'Person'), ('COMPANY', 'Company')], default='PERSON', max_length=10)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('company', models.ForeignKey(blank=True, limit_choices_to={'contact_category': 'COMPANY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['name'],
            },
        ),
    ]
