# Generated by Django 5.0.14 on 2026-02-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, default='Portugal', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='contact',
            name='language',
            field=models.CharField(blank=True, default='pt_PT', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, max_length=255, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_category',
            field=models.CharField(choices=[('PERSON', 'Person'), ('COMPANY', 'Company'), ('BILLING', 'Billing'), ('SHIPPING', 'Shipping'), ('OTHER', 'Other')], default='PERSON', max_length=10),
        ),
    ]
