# Generated by Django 5.0.14 on 2026-02-08 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contacttag_remove_contact_tags_contact_tags'),
        ('core', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='owner_company',
            field=models.ForeignKey(blank=True, help_text='Leave empty for global contacts (all companies). Set to make contact private to specific company.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.company', verbose_name='Owner Company'),
        ),
        migrations.AddField(
            model_name='contacttag',
            name='owner_company',
            field=models.ForeignKey(blank=True, help_text='Leave empty for global tags (all companies). Set to make tag private to specific company.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='core.company', verbose_name='Owner Company'),
        ),
    ]
