# Generated by Django 5.0.14 on 2026-02-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_owner_company_contacttag_owner_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
    ]
