# Generated by Django 5.0.14 on 2026-02-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='associated_contacts',
            field=models.ManyToManyField(blank=True, help_text='Contacts associated with this contact (bidirectional).', related_name='associated_with', to='contacts.contact', verbose_name='Associated Contacts'),
        ),
    ]
