# Generated by Django 5.2.11 on 2026-02-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_associated_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='associated_contacts',
            field=models.ManyToManyField(blank=True, help_text='Contacts associated with this contact (bidirectional).', to='contacts.contact', verbose_name='Associated Contacts'),
        ),
    ]
