# Generated by Django 5.2.11 on 2026-02-23 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0020_remove_company_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Nome único em lowercase com underscores (ex: orcamento_aprovado). Não pode ser alterado após submissão à Meta.', max_length=512, unique=True, verbose_name='Nome técnico')),
                ('display_name', models.CharField(help_text='Nome legível para o utilizador (ex: Orçamento Aprovado).', max_length=255, verbose_name='Nome apresentado')),
                ('category', models.CharField(choices=[('AUTHENTICATION', 'Autenticação'), ('MARKETING', 'Marketing'), ('UTILITY', 'Utilidade')], default='MARKETING', help_text='A categoria determina o custo de envio e as regras da Meta.', max_length=20, verbose_name='Categoria')),
                ('language', models.CharField(choices=[('pt_PT', 'Português (Portugal)'), ('pt_BR', 'Português (Brasil)'), ('en_US', 'Inglês (EUA)'), ('en_GB', 'Inglês (Reino Unido)'), ('fr', 'Francês'), ('es', 'Espanhol'), ('de', 'Alemão'), ('it', 'Italiano'), ('nl', 'Neerlandês'), ('ar', 'Árabe'), ('zh_CN', 'Chinês (Simplificado)')], default='pt_PT', max_length=10, verbose_name='Idioma')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('PAUSED', 'Pausado'), ('DISABLED', 'Desativado')], default='DRAFT', help_text='Estado de aprovação devolvido pela Meta.', max_length=20, verbose_name='Estado')),
                ('allow_category_change', models.BooleanField(default=True, help_text='Permite à Meta reclassificar o template se necessário.', verbose_name='Permitir alteração de categoria')),
                ('header_type', models.CharField(choices=[('NONE', 'Sem cabeçalho'), ('TEXT', 'Texto'), ('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo'), ('DOCUMENT', 'Documento')], default='NONE', max_length=20, verbose_name='Tipo de cabeçalho')),
                ('header_text', models.CharField(blank=True, help_text='Apenas quando o tipo de cabeçalho é "Texto". Máx. 60 caracteres.', max_length=60, verbose_name='Texto do cabeçalho')),
                ('body', models.TextField(help_text='Texto da mensagem. Use {{1}}, {{2}}, … para variáveis dinâmicas.', verbose_name='Corpo da mensagem')),
                ('footer', models.CharField(blank=True, help_text='Texto pequeno no final da mensagem. Máx. 60 caracteres.', max_length=60, verbose_name='Rodapé')),
                ('buttons', models.JSONField(blank=True, default=list, help_text='Lista de botões. Exemplos:\n  URL: {"type": "URL", "text": "Ver orçamento", "url": "https://..."}\n  PHONE_NUMBER: {"type": "PHONE_NUMBER", "text": "Ligar", "phone_number": "+351..."}\n  QUICK_REPLY: {"type": "QUICK_REPLY", "text": "Confirmar"}\n  COPY_CODE: {"type": "COPY_CODE", "example": "ABC123"}', verbose_name='Botões')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Mapeia cada variável {{N}} ao campo do modelo. Exemplo:\n{"1": "contact.name", "2": "title", "3": "estimated_value"}', verbose_name='Mapeamento de variáveis')),
                ('model_name', models.CharField(blank=True, choices=[('', 'Sem modelo específico'), ('crm.Lead', 'CRM — Prospecto/Lead'), ('contacts.Contact', 'Contactos — Contacto'), ('sales.SaleOrder', 'Vendas — Orçamento/Venda'), ('purchases.PurchaseOrder', 'Compras — Encomenda'), ('financial.Invoice', 'Financeiro — Fatura')], help_text='Modelo de Django ao qual este template se aplica (para mapeamento de variáveis).', max_length=100, verbose_name='Modelo associado')),
                ('wa_template_uid', models.CharField(blank=True, help_text='ID devolvido pela Meta após a submissão. Preenchido automaticamente.', max_length=255, verbose_name='ID WhatsApp (Meta)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('owner_company', models.ForeignKey(blank=True, help_text='Empresa proprietária deste template. NULL = global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Template WhatsApp',
                'verbose_name_plural': 'Templates WhatsApp',
                'ordering': ['display_name'],
            },
        ),
    ]
