# Generated by Django 5.0.14 on 2026-02-08 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Legal Name')),
                ('vat', models.CharField(blank=True, max_length=20, verbose_name='VAT/NIF')),
                ('company_registry', models.CharField(blank=True, max_length=50, verbose_name='Company Registry Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='Website')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='Portugal', max_length=100, verbose_name='Country')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Default Currency')),
                ('language', models.CharField(default='pt_PT', max_length=10, verbose_name='Default Language')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Company Logo')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='core.company', verbose_name='Parent Company')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
