# Generated by Django 5.2.11 on 2026-02-13 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('activity_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('STATUS_CHANGE', 'Status Changed'), ('STAGE_CHANGE', 'Stage Changed'), ('ASSIGNMENT', 'Assigned'), ('EMAIL_SENT', 'Email Sent'), ('WHATSAPP_SENT', 'WhatsApp Sent'), ('CALL', 'Phone Call'), ('MEETING', 'Meeting'), ('COMMENT', 'Comment')], max_length=20, verbose_name='Activity Type')),
                ('description', models.TextField(help_text='Human-readable description: "changed stage from New to Qualified"', verbose_name='Description')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured data: {"field": "stage", "old_value": "New", "new_value": "Qualified"}', verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatter_activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chatter Activity',
                'verbose_name_plural': 'Chatter Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_chatte_content_7467a8_idx'), models.Index(fields=['user'], name='core_chatte_user_id_7a52cd_idx'), models.Index(fields=['activity_type'], name='core_chatte_activit_0abf19_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatterMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('object_id', models.UUIDField()),
                ('message_type', models.CharField(choices=[('EMAIL', 'Email'), ('NOTE', 'Internal Note')], default='NOTE', max_length=10, verbose_name='Message Type')),
                ('subject', models.CharField(blank=True, help_text='Only for emails', max_length=255, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Message Body')),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='To')),
                ('cc_emails', models.TextField(blank=True, help_text='Comma-separated email addresses', verbose_name='CC')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment objects: [{"filename": "file.pdf", "url": "/media/..."}]', verbose_name='Attachments')),
                ('is_internal', models.BooleanField(default=False, help_text='True = internal note, False = external communication', verbose_name='Is Internal Note')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the email was sent', null=True, verbose_name='Sent At')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatter_messages', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Chatter Message',
                'verbose_name_plural': 'Chatter Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_chatte_content_5285ac_idx'), models.Index(fields=['author'], name='core_chatte_author__fd0b15_idx'), models.Index(fields=['message_type'], name='core_chatte_message_5b80a0_idx')],
            },
        ),
    ]
