# Generated by Django 5.2.11 on 2026-02-17 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_chatteractivity_chattermessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Ex: "Follow-up Call", "Send Quote Email"', max_length=100, verbose_name='Template Name')),
                ('activity_type', models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('TODO', 'To-Do'), ('WHATSAPP', 'WhatsApp'), ('DOCUMENT', 'Document'), ('SIGNATURE', 'Signature')], max_length=20, verbose_name='Activity Type')),
                ('default_summary', models.CharField(help_text='Pode usar variáveis: {{contact_name}}, {{company_name}}', max_length=255, verbose_name='Default Summary')),
                ('default_description', models.TextField(blank=True, verbose_name='Default Description')),
                ('due_days_offset', models.IntegerField(default=0, help_text='Dias a adicionar à data atual (ex: 3 = daqui a 3 dias)', verbose_name='Due Days Offset')),
                ('default_assigned_to', models.ForeignKey(blank=True, help_text='Responsável padrão (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_templates', to=settings.AUTH_USER_MODEL, verbose_name='Default Assigned To')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL=global template, with value=private to company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_templates', to='core.company', verbose_name='Owner Company')),
            ],
            options={
                'verbose_name': 'Activity Template',
                'verbose_name_plural': 'Activity Templates',
                'ordering': ['name'],
                'unique_together': {('name', 'owner_company')},
            },
        ),
        migrations.CreateModel(
            name='ActivityWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Ex: "Lead Nurturing - First Contact Success"', max_length=100, verbose_name='Workflow Name')),
                ('description', models.TextField(blank=True, help_text='Explicação do workflow', verbose_name='Description')),
                ('trigger_activity_type', models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('TODO', 'To-Do'), ('WHATSAPP', 'WhatsApp'), ('DOCUMENT', 'Document'), ('SIGNATURE', 'Signature')], help_text='Tipo de activity que dispara o workflow', max_length=20, verbose_name='Trigger Activity Type')),
                ('trigger_result', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CALLBACK', 'Callback Later'), ('NO_ANSWER', 'No Answer'), ('NOT_INTERESTED', 'Not Interested')], help_text='Resultado específico (ou None = qualquer resultado)', max_length=20, null=True, verbose_name='Trigger Result')),
                ('trigger_condition', models.JSONField(blank=True, default=dict, help_text='Condições avançadas em JSON (futuro)', verbose_name='Trigger Condition (Advanced)')),
                ('delay_days', models.IntegerField(default=0, help_text='Dias de espera antes de criar próxima activity', verbose_name='Delay (days)')),
                ('is_active', models.BooleanField(default=True, help_text='Desativar para pausar workflow sem deletar', verbose_name='Is Active')),
                ('sequence', models.IntegerField(default=10, help_text='Ordem de execução (menor = primeiro)', verbose_name='Sequence')),
                ('model', models.ForeignKey(help_text='Modelo que dispara este workflow (Lead, Sale, Purchase, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model')),
                ('next_activity_template', models.ForeignKey(help_text='Template da próxima activity a criar', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.activitytemplate', verbose_name='Next Activity Template')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL=global workflow, with value=private to company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_workflows', to='core.company', verbose_name='Owner Company')),
            ],
            options={
                'verbose_name': 'Activity Workflow',
                'verbose_name_plural': 'Activity Workflows',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('object_id', models.UUIDField()),
                ('activity_type', models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('TODO', 'To-Do'), ('WHATSAPP', 'WhatsApp'), ('DOCUMENT', 'Document'), ('SIGNATURE', 'Signature')], max_length=20, verbose_name='Activity Type')),
                ('summary', models.CharField(max_length=255, verbose_name='Summary')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='Due Time')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is Done')),
                ('done_date', models.DateTimeField(blank=True, null=True, verbose_name='Done Date')),
                ('result', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CALLBACK', 'Callback Later'), ('NO_ANSWER', 'No Answer'), ('NOT_INTERESTED', 'Not Interested')], help_text='Resultado usado para workflows automáticos', max_length=20, null=True, verbose_name='Result')),
                ('feedback', models.TextField(blank=True, help_text='Notas quando marcar como concluída', verbose_name='Feedback')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_activities', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_activities', to='core.company', verbose_name='Owner Company')),
                ('template', models.ForeignKey(blank=True, help_text='Template usado para criar esta activity (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.activitytemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Scheduled Activity',
                'verbose_name_plural': 'Scheduled Activities',
                'ordering': ['due_date', 'due_time', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_schedu_content_485c20_idx'), models.Index(fields=['assigned_to'], name='core_schedu_assigne_b8d3f5_idx'), models.Index(fields=['due_date'], name='core_schedu_due_dat_a36ecb_idx'), models.Index(fields=['is_done'], name='core_schedu_is_done_f82980_idx')],
            },
        ),
    ]
