# Generated by Django 5.2.11 on 2026-02-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitytemplate_activityworkflow_scheduledactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytemplate',
            name='action_code',
            field=models.TextField(blank=True, help_text='Código Python a executar ao criar/completar activity (avançado)', verbose_name='Action Code (Python)'),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='auto_delete_done_after_days',
            field=models.IntegerField(blank=True, help_text='Se keep_done=False, deletar após quantos dias? (NULL=nunca deletar)', null=True, verbose_name='Auto-delete Done After (days)'),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='decoration_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('warning', 'Warning (Orange)'), ('danger', 'Danger (Red)'), ('success', 'Success (Green)'), ('info', 'Info (Blue)')], help_text='Cor/estilo visual na interface', max_length=20, verbose_name='Decoration Type'),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class (ex: fa-phone, fa-envelope) ou emoji', max_length=50, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='keep_done_activities',
            field=models.BooleanField(default=True, help_text='Se False, activities done deste tipo são auto-deletadas após X dias', verbose_name='Keep Done Activities'),
        ),
        migrations.AddField(
            model_name='activityworkflow',
            name='base_date_type',
            field=models.CharField(choices=[('DEADLINE', 'After Previous Activity Deadline'), ('COMPLETION', 'After Previous Activity Completion Date')], default='COMPLETION', help_text='Calcular próxima activity baseado em deadline (due_date) ou completion (done_date)', max_length=20, verbose_name='Base Date Type'),
        ),
        migrations.AddField(
            model_name='activityworkflow',
            name='chaining_mode',
            field=models.CharField(choices=[('SUGGEST', 'Suggest Next Activity'), ('TRIGGER', 'Trigger Next Activity')], default='SUGGEST', help_text='SUGGEST = mostrar modal de confirmação | TRIGGER = criar automaticamente', max_length=20, verbose_name='Chaining Mode'),
        ),
    ]
