# Generated by Django 5.2.11 on 2026-02-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activitytemplate_action_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytemplate',
            name='icon_color',
            field=models.CharField(blank=True, default='#6366F1', help_text='Cor do SVG em hexadecimal (ex: #FF5733, #6366F1). Aplicado via CSS color property.', max_length=7, verbose_name='Icon Color'),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Opção 3: SVG inline. Usar currentColor para cor dinâmica. Ex: <svg><path fill="currentColor" d="..."/></svg>', verbose_name='Icon SVG (Custom)'),
        ),
        migrations.AlterField(
            model_name='activitytemplate',
            name='icon',
            field=models.CharField(blank=True, help_text='Opção 1: FontAwesome (ex: fa-phone) | Opção 2: Emoji (ex: 📞) | Deixar vazio se usar SVG', max_length=50, verbose_name='Icon (FontAwesome ou Emoji)'),
        ),
    ]
