# Generated by Django 5.2.11 on 2026-02-18 01:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_activitytemplate_icon_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Ex: "Follow-up pós-reunião", "Onboarding novo cliente"', max_length=255, verbose_name='Chain Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Activity Chain',
                'verbose_name_plural': 'Activity Chains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityChainInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused')], default='IN_PROGRESS', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Activity Chain Instance',
                'verbose_name_plural': 'Activity Chain Instances',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityChainStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Ordem de execução dentro da cadeia (1, 2, 3...)', verbose_name='Order')),
                ('delay_days', models.IntegerField(default=0, help_text='Dias de espera após o passo anterior ser concluído (0 = executa logo)', verbose_name='Delay (days)')),
            ],
            options={
                'verbose_name': 'Activity Chain Step',
                'verbose_name_plural': 'Activity Chain Steps',
                'ordering': ['chain', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Executed At')),
                ('result', models.CharField(blank=True, choices=[('SUCCESS', 'Sucesso'), ('FAILED', 'Falhado'), ('CALLBACK', 'Ligar mais tarde'), ('NO_ANSWER', 'Sem resposta'), ('NOT_INTERESTED', 'Não interessado'), ('PENDING', 'Pendente')], max_length=20, null=True, verbose_name='Result')),
                ('notes', models.TextField(blank=True, help_text='Detalhes sobre o que aconteceu nesta atividade', verbose_name='Notes')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='Due Time')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is Done')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Done At')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['chain_instance', 'step__order'],
            },
        ),
        migrations.AlterModelOptions(
            name='scheduledactivity',
            options={'ordering': ['activity_type', 'summary'], 'verbose_name': 'Scheduled Activity', 'verbose_name_plural': 'Scheduled Activities'},
        ),
        migrations.RemoveIndex(
            model_name='scheduledactivity',
            name='core_schedu_content_485c20_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduledactivity',
            name='core_schedu_assigne_b8d3f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduledactivity',
            name='core_schedu_due_dat_a36ecb_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduledactivity',
            name='core_schedu_is_done_f82980_idx',
        ),
        migrations.RemoveField(
            model_name='scheduledactivity',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='scheduledactivity',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='scheduledactivity',
            name='done_date',
        ),
        migrations.RemoveField(
            model_name='scheduledactivity',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='scheduledactivity',
            name='due_time',
        ),
        migrations.RemoveField(
            model_name='scheduledactivity',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='scheduledactivity',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='scheduledactivity',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='scheduledactivity',
            name='result',
        ),
        migrations.RemoveField(
            model_name='scheduledactivity',
            name='template',
        ),
        migrations.AlterField(
            model_name='activityworkflow',
            name='trigger_result',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'Sucesso'), ('FAILED', 'Falhado'), ('CALLBACK', 'Ligar mais tarde'), ('NO_ANSWER', 'Sem resposta'), ('NOT_INTERESTED', 'Não interessado'), ('PENDING', 'Pendente')], help_text='Resultado específico (ou None = qualquer resultado)', max_length=20, null=True, verbose_name='Trigger Result'),
        ),
        migrations.AlterField(
            model_name='scheduledactivity',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada do que deve ser feito', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='scheduledactivity',
            name='summary',
            field=models.CharField(help_text='Título da atividade (ex: "Ligar ao cliente", "Enviar proposta")', max_length=255, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='activitychain',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_chains', to='core.company', verbose_name='Owner Company'),
        ),
        migrations.AddField(
            model_name='activitychaininstance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chain_instances', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='activitychaininstance',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.activitychain', verbose_name='Chain'),
        ),
        migrations.AddField(
            model_name='activitychaininstance',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='activitychaininstance',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_instances', to='core.company', verbose_name='Owner Company'),
        ),
        migrations.AddField(
            model_name='activitychainstep',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_steps', to='core.scheduledactivity', verbose_name='Activity Blueprint'),
        ),
        migrations.AddField(
            model_name='activitychainstep',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.activitychain', verbose_name='Chain'),
        ),
        migrations.AddField(
            model_name='activitychainstep',
            name='default_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chain_step_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Default Assigned To'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='chain_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.activitychaininstance', verbose_name='Chain Instance'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_activities', to=settings.AUTH_USER_MODEL, verbose_name='Logged By'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.activitychainstep', verbose_name='Step'),
        ),
        migrations.AddIndex(
            model_name='activitychaininstance',
            index=models.Index(fields=['content_type', 'object_id'], name='core_activi_content_d404e9_idx'),
        ),
        migrations.AddIndex(
            model_name='activitychaininstance',
            index=models.Index(fields=['status'], name='core_activi_status_005c89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activitychainstep',
            unique_together={('chain', 'order')},
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['chain_instance', 'step'], name='core_activi_chain_i_052472_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['is_done'], name='core_activi_is_done_289c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['due_date'], name='core_activi_due_dat_4fbe54_idx'),
        ),
    ]
