# Generated by Django 5.2.11 on 2026-02-18 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_redesign_scheduled_activity_and_chain_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityworkflow',
            name='next_activity_template',
            field=models.ForeignKey(help_text='Blueprint da próxima activity a criar', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.scheduledactivity', verbose_name='Next Activity Blueprint'),
        ),
        migrations.AlterModelOptions(
            name='scheduledactivity',
            options={'ordering': ['activity_type', 'name', 'summary'], 'verbose_name': 'Scheduled Activity', 'verbose_name_plural': 'Scheduled Activities'},
        ),
        migrations.AddField(
            model_name='scheduledactivity',
            name='decoration_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('warning', 'Warning (Orange)'), ('danger', 'Danger (Red)'), ('success', 'Success (Green)'), ('info', 'Info (Blue)')], help_text='Cor/estilo visual na interface', max_length=20, verbose_name='Decoration Type'),
        ),
        migrations.AddField(
            model_name='scheduledactivity',
            name='icon',
            field=models.CharField(blank=True, help_text='Opcional: ícone FontAwesome (ex: fa-phone) ou Emoji (ex: 📞). Deixar vazio se usar SVG.', max_length=50, verbose_name='Icon (FontAwesome ou Emoji)'),
        ),
        migrations.AddField(
            model_name='scheduledactivity',
            name='icon_color',
            field=models.CharField(blank=True, default='#6366F1', help_text='Cor do ícone em hexadecimal (ex: #FF5733, #6366F1)', max_length=7, verbose_name='Icon Color'),
        ),
        migrations.AddField(
            model_name='scheduledactivity',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG inline com currentColor para cor dinâmica', verbose_name='Icon SVG'),
        ),
        migrations.AddField(
            model_name='scheduledactivity',
            name='name',
            field=models.CharField(blank=True, help_text='Label para identificar o blueprint (ex: "Primeira Ligação", "Follow-up Email")', max_length=100, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='ActivityTemplate',
        ),
    ]
