# Generated by Django 5.2.11 on 2026-02-18 02:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_activitytemplate_into_scheduledactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Nome visível (ex: "Phone Call", "Email")', max_length=100, verbose_name='Nome')),
                ('code', models.CharField(help_text='Identificador único em maiúsculas (ex: CALL, EMAIL). Não alterar após criar workflows.', max_length=50, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Activity Type',
                'verbose_name_plural': 'Activity Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='scheduledactivity',
            options={'ordering': ['activity_type__name', 'name', 'summary'], 'verbose_name': 'Scheduled Activity', 'verbose_name_plural': 'Scheduled Activities'},
        ),
        migrations.AlterField(
            model_name='activityworkflow',
            name='trigger_activity_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de activity que dispara o workflow', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.activitytype', verbose_name='Trigger Activity Type'),
        ),
        migrations.AlterField(
            model_name='scheduledactivity',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blueprints', to='core.activitytype', verbose_name='Activity Type'),
        ),
    ]
