# Generated by Django 5.2.11 on 2026-02-19 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_create_activity_type_and_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitychain',
            name='applicable_model',
            field=models.CharField(choices=[('lead', 'Lead'), ('contact', 'Contacto')], default='lead', help_text='Qual o modelo a que esta cadeia se aplica (Lead, Contacto...)', max_length=50, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='activitychainstep',
            name='on_failure_activity',
            field=models.ForeignKey(blank=True, help_text='Blueprint a executar quando este passo falha (ex: "Não Atendeu"). Vazio = avança igualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chain_steps_on_failure', to='core.scheduledactivity', verbose_name='Atividade se Insucesso'),
        ),
        migrations.AddField(
            model_name='activitychainstep',
            name='on_failure_delay_days',
            field=models.IntegerField(default=1, help_text='Dias de espera antes de executar a atividade de insucesso', verbose_name='Delay Insucesso (dias)'),
        ),
    ]
