# Generated by Django 5.2.11 on 2026-02-19 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0011_activitychain_applicable_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('object_id', models.UUIDField(verbose_name='Object ID')),
                ('summary', models.CharField(help_text='Título curto da atividade', max_length=255, verbose_name='Summary')),
                ('note', models.TextField(blank=True, help_text='Nota opcional', verbose_name='Note')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('PLANNED', 'Planeada'), ('DONE', 'Concluída'), ('CANCELLED', 'Cancelada')], default='PLANNED', max_length=20, verbose_name='Status')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Done At')),
                ('done_note', models.TextField(blank=True, help_text='Nota adicionada ao marcar como concluída', verbose_name='Done Note')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_activities', to='core.activitytype', verbose_name='Activity Type')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_activities_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_activities_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Planned Activity',
                'verbose_name_plural': 'Planned Activities',
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_planne_content_d28790_idx'), models.Index(fields=['status'], name='core_planne_status_55b9f8_idx'), models.Index(fields=['assigned_to'], name='core_planne_assigne_65b0cb_idx'), models.Index(fields=['due_date'], name='core_planne_due_dat_bc3eb5_idx')],
            },
        ),
    ]
