# Generated by Django 5.2.11 on 2026-02-19 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_planned_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_type', models.CharField(choices=[('ACTIVITY_OVERDUE', 'Atividade em Atraso'), ('ACTIVITY_TODAY', 'Atividade para Hoje'), ('ACTIVITY_UPCOMING', 'Atividade Futura'), ('MENTION', 'Menção'), ('ASSIGNMENT', 'Atribuição'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('STAGE_CHANGE', 'Mudança de Etapa'), ('COMMENT', 'Comentário'), ('SYSTEM', 'Sistema')], max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida a')),
                ('priority', models.PositiveSmallIntegerField(default=99, verbose_name='Prioridade')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'), models.Index(fields=['user', 'priority', '-created_at'], name='core_notifi_user_id_817bae_idx')],
            },
        ),
    ]
