# Generated by Django 5.2.11 on 2026-02-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Urgente'),
        ),
    ]
