# Generated by Django 5.2.11 on 2026-02-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notification_is_urgent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattermessage',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Enviado'), ('inbound', 'Recebido')], default='outbound', help_text='outbound = enviado pelo utilizador; inbound = recebido do cliente (IMAP futuro)', max_length=8, verbose_name='Direção'),
        ),
        migrations.AddField(
            model_name='chattermessage',
            name='from_email',
            field=models.EmailField(blank=True, help_text='Remetente real do email — preenchido para outbound e inbound.', max_length=254, verbose_name='De (email)'),
        ),
        migrations.AddField(
            model_name='chattermessage',
            name='in_reply_to',
            field=models.CharField(blank=True, help_text='Header In-Reply-To do email recebido. Permite ligar respostas à thread.', max_length=998, verbose_name='In-Reply-To'),
        ),
        migrations.AddField(
            model_name='chattermessage',
            name='message_id',
            field=models.CharField(blank=True, help_text='Header Message-ID SMTP. Utilizado para fazer match de respostas (IMAP futuro).', max_length=998, verbose_name='Message-ID'),
        ),
    ]
