# Generated by Django 5.2.11 on 2026-02-22 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0017_chattermessage_body_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatterFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(verbose_name='ID do Objeto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatter_follows_added', to=settings.AUTH_USER_MODEL, verbose_name='Adicionado por')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Objeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatter_follows', to=settings.AUTH_USER_MODEL, verbose_name='Seguidor')),
            ],
            options={
                'verbose_name': 'Seguidor do Chatter',
                'verbose_name_plural': 'Seguidores do Chatter',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_chatte_content_01d5f9_idx')],
                'unique_together': {('content_type', 'object_id', 'user')},
            },
        ),
    ]
