# Generated by Django 5.2.11 on 2026-02-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_chatterfollower'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(help_text='Meta Business Manager → WhatsApp → Phone Number ID', max_length=50, verbose_name='Phone Number ID')),
                ('business_account_id', models.CharField(blank=True, max_length=50, verbose_name='Business Account ID (WABA)')),
                ('access_token', models.TextField(help_text='Permanent / System User token from Meta — stored encrypted', verbose_name='Access Token (encriptado)')),
                ('webhook_verify_token', models.CharField(help_text='Arbitrary secret string set in Meta App → Webhooks configuration', max_length=100, verbose_name='Webhook Verify Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração WhatsApp',
                'verbose_name_plural': 'Configurações WhatsApp',
            },
        ),
    ]
