# Generated by Django 5.2.11 on 2026-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_companywhatsappconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='language',
        ),
        migrations.AlterField(
            model_name='chattermessage',
            name='message_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('NOTE', 'Internal Note'), ('WHATSAPP', 'WhatsApp')], default='NOTE', max_length=10, verbose_name='Message Type'),
        ),
    ]
