# Generated by Django 5.2.11 on 2026-02-23 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0020_remove_company_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('object_id', models.CharField(max_length=255, verbose_name='ID do objeto')),
                ('activity_type', models.CharField(choices=[('TODO', 'To-Do'), ('EMAIL', 'Email'), ('CALL', 'Chamada'), ('WHATSAPP', 'WhatsApp'), ('DOCUMENT', 'Documento'), ('SIGNATURE', 'Assinatura'), ('MEETING', 'Reunião')], default='TODO', max_length=20, verbose_name='Tipo')),
                ('summary', models.CharField(max_length=255, verbose_name='Resumo')),
                ('due_date', models.DateField(verbose_name='Data limite')),
                ('is_done', models.BooleanField(default=False, verbose_name='Concluído')),
                ('done_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='Feedback')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_activities', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_activities', to='core.company', verbose_name='Empresa')),
                ('scheduled_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_activities', to='core.scheduledactivity', verbose_name='Blueprint')),
            ],
            options={
                'verbose_name': 'Atividade Genérica',
                'verbose_name_plural': 'Atividades Genéricas',
                'ordering': ['due_date', 'created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_generi_content_b5ab82_idx'), models.Index(fields=['due_date'], name='core_generi_due_dat_8ef17c_idx'), models.Index(fields=['is_done'], name='core_generi_is_done_4442c4_idx')],
            },
        ),
    ]
