# Generated by Django 5.2.11 on 2026-02-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_generic_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledactivity',
            name='applicable_models',
            field=models.JSONField(blank=True, default=list, help_text='Deixar vazio para aplicar a todos os módulos. Selecionar módulos específicos para filtrar a visibilidade.', verbose_name='Modelos aplicáveis'),
        ),
    ]
