# Generated by Django 5.2.11 on 2026-02-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_scheduledactivity_applicable_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email de envio (SMTP)')),
                ('app_password', models.TextField(help_text='Gmail App Password ou senha de aplicação — guardada cifrada', verbose_name='App Password (encriptada)')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Microsoft 365')], default='gmail', max_length=10, verbose_name='Fornecedor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Email',
                'verbose_name_plural': 'Configurações Email',
            },
        ),
    ]
