# Generated by Django 5.2.11 on 2026-02-28 00:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_email_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Nome legível (ex: Envio de Orçamento, Follow-up Comercial).', max_length=255, verbose_name='Nome do template')),
                ('module', models.CharField(choices=[('CRM', 'CRM'), ('SALES', 'Vendas'), ('PURCHASES', 'Compras'), ('INVOICING', 'Faturação'), ('CONTACTS', 'Contactos'), ('MARKETING', 'Marketing'), ('GENERAL', 'Geral')], db_index=True, default='GENERAL', help_text='Módulo onde este template fica disponível.', max_length=20, verbose_name='Módulo')),
                ('language', models.CharField(choices=[('pt_PT', 'Português (Portugal)'), ('pt_BR', 'Português (Brasil)'), ('en_US', 'Inglês (EUA)'), ('en_GB', 'Inglês (Reino Unido)'), ('fr', 'Francês'), ('es', 'Espanhol')], default='pt_PT', max_length=10, verbose_name='Idioma')),
                ('subject', models.CharField(help_text='Assunto do email. Suporta placeholders: {{ contact_name }}, {{ lead_title }}, etc.', max_length=500, verbose_name='Assunto')),
                ('body_html', models.TextField(help_text='Conteúdo HTML do email. Suporta placeholders Django template.', verbose_name='Corpo HTML')),
                ('available_placeholders', models.JSONField(blank=True, default=dict, help_text='Mapa de placeholders e suas descrições. Exemplo:\n{"contact_name": "Nome do contacto", "lead_title": "Título da lead"}', verbose_name='Placeholders disponíveis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='core.company', verbose_name='Empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Template de Email',
                'verbose_name_plural': 'Templates de Email',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('STATIC', 'Ficheiro estático'), ('REPORT', 'Relatório dinâmico')], default='STATIC', max_length=10, verbose_name='Tipo de anexo')),
                ('file', models.FileField(blank=True, help_text='Ficheiro estático a anexar (PDF, imagem, etc.).', upload_to='email_templates/attachments/%Y/%m/', verbose_name='Ficheiro')),
                ('report_type', models.CharField(blank=True, choices=[('QUOTE', 'Orçamento'), ('INVOICE', 'Fatura'), ('PURCHASE_ORDER', 'Ordem de Compra'), ('DELIVERY_NOTE', 'Guia de Remessa')], help_text='Tipo de documento a gerar automaticamente (fase futura).', max_length=30, verbose_name='Tipo de relatório')),
                ('filename', models.CharField(blank=True, help_text='Nome com que o anexo será enviado. Suporta placeholders (ex: orcamento_{{ lead_title }}.pdf).', max_length=255, verbose_name='Nome do ficheiro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.emailtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Anexo de Template',
                'verbose_name_plural': 'Anexos de Template',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(fields=('name', 'owner_company'), name='unique_email_template_name_per_company'),
        ),
    ]
