# Generated by Django 5.2.11 on 2026-02-28 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_email_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='owner_company',
            field=models.ForeignKey(blank=True, help_text='Deixar vazio para templates globais (disponíveis a todas as empresas).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_company__isnull', True)), fields=('name',), name='unique_global_email_template_name'),
        ),
    ]
