# Generated by Django 5.2.11 on 2026-02-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_email_template_owner_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('BASE', 'Base (sistema)'), ('CUSTOM', 'Personalizado')], db_index=True, default='CUSTOM', help_text='BASE = template do sistema (não eliminável). CUSTOM = criado pelo utilizador.', max_length=10, verbose_name='Tipo'),
        ),
    ]
