# Generated by Django 5.2.11 on 2026-02-28 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0028_email_template_default_body_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('header_html', models.TextField(help_text='HTML do cabeçalho do documento. Usa placeholders Django template.', verbose_name='HTML do Header')),
                ('footer_html', models.TextField(help_text='HTML do rodapé do documento. Usa placeholders Django template.', verbose_name='HTML do Footer')),
                ('preview_image', models.ImageField(blank=True, default='', upload_to='documents/previews/layouts/', verbose_name='Imagem de Pré-visualização')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_styles_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_styles_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Estilo de Layout',
                'verbose_name_plural': 'Estilos de Layout',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TableStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('css_styles', models.TextField(help_text='CSS inline para estilizar a tabela de dados.', verbose_name='CSS da Tabela')),
                ('header_row_html', models.TextField(blank=True, default='', help_text='HTML template da row de cabeçalho (th).', verbose_name='HTML do Header da Tabela')),
                ('data_row_html', models.TextField(blank=True, default='', help_text='HTML template de cada linha de dados (td).', verbose_name='HTML de cada Row de Dados')),
                ('totals_row_html', models.TextField(blank=True, default='', help_text='HTML template do bloco de totais (subtotal, IVA, total).', verbose_name='HTML da Row de Totais')),
                ('preview_image', models.ImageField(blank=True, default='', upload_to='documents/previews/tables/', verbose_name='Imagem de Pré-visualização')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_styles_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_styles_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Estilo de Tabela',
                'verbose_name_plural': 'Estilos de Tabela',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('font', models.CharField(default='Lato', max_length=100, verbose_name='Fonte')),
                ('primary_color', models.CharField(default='#dbc693', help_text='Cor HEX para headers e destaques.', max_length=7, verbose_name='Cor Principal')),
                ('secondary_color', models.CharField(default='#1f2937', help_text='Cor HEX para texto e borders.', max_length=7, verbose_name='Cor Secundária')),
                ('tagline', models.CharField(blank=True, default='', max_length=255, verbose_name='Slogan')),
                ('footer_text', models.TextField(blank=True, default='', help_text='Texto livre: telefone, email, website.', verbose_name='Texto do Rodapé')),
                ('paper_format', models.CharField(choices=[('A4', 'A4'), ('US_LETTER', 'US Letter')], default='A4', max_length=20, verbose_name='Formato do Papel')),
                ('tax_id', models.CharField(blank=True, default='', max_length=50, verbose_name='NIF / CNPJ')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_layout', to='core.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_layouts_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_layouts_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('layout_style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_layouts', to='documents.layoutstyle', verbose_name='Estilo de Layout')),
                ('table_style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_layouts', to='documents.tablestyle', verbose_name='Estilo de Tabela')),
            ],
            options={
                'verbose_name': 'Layout de Documento',
                'verbose_name_plural': 'Layouts de Documento',
            },
        ),
    ]
