# Generated by Django 5.2.11 on 2026-02-28 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0028_email_template_default_body_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('owner_company', models.ForeignKey(blank=True, help_text='Empresa proprietária. NULL = global (visível para todas).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='core.company', verbose_name='Empresa')),
                ('parent', models.ForeignKey(blank=True, help_text='Deixe vazio para categoria de topo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
                'unique_together': {('name', 'parent', 'owner_company')},
            },
        ),
    ]
