# Generated by Django 5.2.11 on 2026-02-28 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_email_template_default_body_path'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UoMCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL = global (visível para todas).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_categories', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoria de UdM',
                'verbose_name_plural': 'Categorias de UdM',
                'ordering': ['name'],
                'unique_together': {('name', 'owner_company')},
            },
        ),
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('symbol', models.CharField(help_text='Ex: kg, g, L, mL', max_length=16, verbose_name='Símbolo')),
                ('uom_type', models.CharField(choices=[('reference', 'Referência'), ('bigger', 'Maior que a referência'), ('smaller', 'Menor que a referência')], default='reference', help_text='Referência = unidade base da categoria.', max_length=16, verbose_name='Tipo')),
                ('factor', models.DecimalField(decimal_places=10, default=1, help_text='Quantas unidades de referência equivale 1 desta unidade. Ex: 1 kg = 1000 g → factor = 1000.', max_digits=20, verbose_name='Factor')),
                ('rounding', models.DecimalField(decimal_places=6, default=0.01, help_text='Precisão mínima para esta unidade.', max_digits=12, verbose_name='Precisão de arredondamento')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL = global (visível para todas).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uoms', to='core.company', verbose_name='Empresa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uoms', to='inventory.uomcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['category', 'uom_type', 'name'],
                'unique_together': {('name', 'category', 'owner_company')},
            },
        ),
    ]
