# Generated by Django 5.2.11 on 2026-02-28 20:30

import apps.inventory.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_associated_contacts'),
        ('core', '0028_email_template_default_body_path'),
        ('inventory', '0002_uom_category_and_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('internal_reference', models.CharField(blank=True, default='', help_text='Código único do produto (ex: FM-001).', max_length=64, verbose_name='Referência Interna')),
                ('reference', models.CharField(blank=True, default='', help_text='Campo de texto livre.', max_length=255, verbose_name='Referência')),
                ('barcode', models.CharField(blank=True, default='', help_text='EAN-13, UPC, etc.', max_length=64, verbose_name='Código de Barras')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.inventory.models.product_image_path, verbose_name='Imagem')),
                ('product_type', models.CharField(choices=[('storable', 'Armazenável'), ('consumable', 'Consumível'), ('service', 'Serviço')], default='storable', help_text='Armazenável = com stock. Consumível = sem controlo. Serviço = sem stock.', max_length=16, verbose_name='Tipo de Produto')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, help_text='Preço de venda em €.', max_digits=10, verbose_name='Preço de Venda')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Custo unitário em €.', max_digits=10, verbose_name='Preço de Custo')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=23, help_text='Percentagem de IVA aplicável.', max_digits=5, verbose_name='Taxa IVA (%)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category', verbose_name='Categoria')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL = global (visível para todas).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.company', verbose_name='Empresa')),
                ('supplier', models.ForeignKey(blank=True, help_text='Fornecedor principal deste produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='contacts.contact', verbose_name='Fornecedor')),
                ('uom', models.ForeignKey(help_text='UdM principal (stock e venda).', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.uom', verbose_name='Unidade de Medida')),
                ('uom_purchase', models.ForeignKey(blank=True, help_text='UdM usada nas compras (pode diferir). Ex: compra em caixas, vende à unidade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_purchase', to='inventory.uom', verbose_name='UdM de Compra')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('internal_reference__gt', '')), fields=('internal_reference', 'owner_company'), name='unique_product_internal_ref_per_company'), models.UniqueConstraint(condition=models.Q(('barcode__gt', '')), fields=('barcode', 'owner_company'), name='unique_product_barcode_per_company')],
            },
        ),
    ]
