# Generated by Django 5.2.11 on 2026-02-28 23:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_email_template_default_body_path'),
        ('inventory', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Ex: Armazém Principal', max_length=128, verbose_name='Nome')),
                ('code', models.CharField(help_text='Código curto, ex: WH', max_length=5, verbose_name='Código')),
                ('address', models.TextField(blank=True, default='', verbose_name='Morada')),
                ('is_default', models.BooleanField(default=False, help_text='Apenas 1 armazém pode ser padrão por empresa.', verbose_name='Armazém Padrão')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL = global (visível para todas).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Armazém',
                'verbose_name_plural': 'Armazéns',
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(fields=('code', 'owner_company'), name='unique_warehouse_code_per_company')],
            },
        ),
    ]
