# Generated by Django 5.2.11 on 2026-03-01 11:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_associated_contacts'),
        ('core', '0028_email_template_default_body_path'),
        ('inventory', '0004_add_warehouse_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reference', models.CharField(help_text='Auto-gerado: WH/IN/00001, WH/OUT/00001, ADJ/00001', max_length=32, unique=True, verbose_name='Referência')),
                ('movement_type', models.CharField(choices=[('receipt', 'Receção'), ('delivery', 'Expedição'), ('adjustment', 'Ajuste')], max_length=16, verbose_name='Tipo de Movimento')),
                ('state', models.CharField(choices=[('draft', 'Rascunho'), ('done', 'Validado'), ('cancelled', 'Cancelado')], default='draft', max_length=16, verbose_name='Estado')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Movimento')),
                ('origin', models.CharField(blank=True, default='', help_text='Referência ao documento de origem (ex: PO-00001).', max_length=64, verbose_name='Origem')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL = global (visível para todas).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.company', verbose_name='Empresa')),
                ('partner', models.ForeignKey(blank=True, help_text='Fornecedor (receção) ou cliente (expedição).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='contacts.contact', verbose_name='Parceiro')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse', verbose_name='Armazém')),
            ],
            options={
                'verbose_name': 'Movimento de Stock',
                'verbose_name_plural': 'Movimentos de Stock',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
