# Generated by Django 5.2.11 on 2026-03-01 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantidade movida nesta linha.', max_digits=14, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Custo unitário (receção) ou preço de venda (expedição).', max_digits=10, verbose_name='Preço Unitário')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_lines', to='inventory.product', verbose_name='Produto')),
                ('stock_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockmovement', verbose_name='Movimento')),
                ('uom', models.ForeignKey(blank=True, help_text='Herdado do produto se não definido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_lines', to='inventory.uom', verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Linha de Movimento',
                'verbose_name_plural': 'Linhas de Movimento',
                'ordering': ['created_at'],
            },
        ),
    ]
