# Generated by Django 5.2.11 on 2026-03-01 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockmovementline'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, help_text='Quantidade física actual neste armazém.', max_digits=14, verbose_name='Quantidade em Mão')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quants', to='inventory.product', verbose_name='Produto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quants', to='inventory.warehouse', verbose_name='Armazém')),
            ],
            options={
                'verbose_name': 'Stock Actual',
                'verbose_name_plural': 'Stock Actual',
                'ordering': ['product__name', 'warehouse__name'],
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
