# Generated by Django 5.2.11 on 2026-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockquant'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Copiado do produto aquando da criação da linha.', max_digits=5, verbose_name='Taxa IVA (%)'),
        ),
    ]
