# Generated by Django 5.2.11 on 2026-03-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockmovementline_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantidade movida nesta linha. Usa decimais para sub-unidades (ex: 0.250 = 250 g de 1 kg).', max_digits=14, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='stockquant',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantidade física actual neste armazém.', max_digits=14, verbose_name='Quantidade em Mão'),
        ),
    ]
