# Generated by Django 5.2.11 on 2026-03-01 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_associated_contacts'),
        ('core', '0029_document_sequence'),
        ('inventory', '0009_decimal_places_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupplierInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=10, help_text='Prioridade de compra. Menor número = mais prioritário.', verbose_name='Sequência')),
                ('supplier_product_code', models.CharField(blank=True, default='', help_text='Código que o fornecedor usa para este produto nas suas faturas/catálogo. Usado para matching automático na leitura de PDFs (Fase 14).', max_length=64, verbose_name='Cód. Fornecedor')),
                ('price', models.DecimalField(decimal_places=4, default=0, help_text='Preço unitário na UdM de compra do produto. Atualizado automaticamente ao receber faturas.', max_digits=12, verbose_name='Preço de Compra')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=1, help_text='Quantidade mínima de encomenda neste fornecedor.', max_digits=12, verbose_name='Qtd. Mínima')),
                ('lead_time', models.PositiveSmallIntegerField(default=0, help_text='Prazo de entrega em dias úteis.', verbose_name='Prazo (dias)')),
                ('is_preferred', models.BooleanField(default=False, help_text='Atalho: assinala este como o fornecedor preferido independentemente da sequência.', verbose_name='Preferido')),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_supplier_infos', to='core.company', verbose_name='Empresa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_infos', to='inventory.product', verbose_name='Produto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_supplier_infos', to='contacts.contact', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Info Fornecedor',
                'verbose_name_plural': 'Info Fornecedores',
                'ordering': ['sequence', '-is_preferred', 'price'],
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
