# Generated by Django 5.2.11 on 2026-03-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_product_min_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='adjustment_direction',
            field=models.CharField(blank=True, choices=[('in', 'Entrada (adiciona stock)'), ('out', 'Saída (remove stock)')], help_text='Apenas para ajustes: Entrada adiciona stock, Saída remove stock.', max_length=3, null=True, verbose_name='Direção do Ajuste'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Alerta quando o stock em mão cair abaixo deste valor.', max_digits=12, verbose_name='Stock Mínimo'),
        ),
    ]
