# Generated by Django 5.2.11 on 2026-03-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_adjustment_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementline',
            name='cost_price_at_move',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Custo Médio Ponderado (CMVMC) do produto no instante em que este movimento foi validado. Preenchido automaticamente. Imutável após validação.', max_digits=10, null=True, verbose_name='Custo Médio no Momento'),
        ),
    ]
