# Generated by Django 5.2.11 on 2026-03-03 22:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_associated_contacts'),
        ('core', '0029_document_sequence'),
        ('inventory', '0014_add_scrap_movement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Ex: Compras Semana 10 — gerado automaticamente se deixado em branco.', max_length=200, verbose_name='Nome')),
                ('state', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmada'), ('done', 'Concluída'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Estado')),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Data prevista para a compra.', verbose_name='Data Prevista')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Referência Externa')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_lists', to='core.company', verbose_name='Empresa')),
                ('supplier', models.ForeignKey(blank=True, help_text='Local / fornecedor onde vai ser feita a compra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lists', to='contacts.contact', verbose_name='Fornecedor')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Armazém de destino dos produtos comprados.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lists', to='inventory.warehouse', verbose_name='Armazém')),
            ],
            options={
                'verbose_name': 'Lista de Compras',
                'verbose_name_plural': 'Listas de Compras',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseListLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=0, help_text='Valor gravado no momento de criação/geração da linha.', max_digits=14, verbose_name='Stock Actual')),
                ('qty_needed', models.DecimalField(decimal_places=4, default=0, help_text='Stock mínimo alvo gravado no momento da geração.', max_digits=14, verbose_name='Qtd. Necessária')),
                ('qty_to_buy', models.DecimalField(decimal_places=4, default=0, help_text='Sugerida automaticamente; editável pelo utilizador.', max_digits=14, verbose_name='Qtd. a Comprar')),
                ('purchase_price', models.DecimalField(decimal_places=4, default=0, help_text='Preço unitário sem IVA.', max_digits=14, verbose_name='Preço de Compra')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, help_text='Ex: 23.00 para 23%.', max_digits=6, verbose_name='Taxa IVA (%)')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_list_lines', to='inventory.product', verbose_name='Produto')),
                ('purchase_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaselist', verbose_name='Lista de Compras')),
                ('uom', models.ForeignKey(blank=True, help_text='Preenchida automaticamente a partir do produto; editável para comprar noutra unidade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_list_lines', to='inventory.uom', verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Linha de Lista de Compras',
                'verbose_name_plural': 'Linhas de Lista de Compras',
                'ordering': ['id'],
            },
        ),
    ]
