# Generated by Django 5.2.11 on 2026-03-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_purchaselist_purchaselistline'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselistline',
            name='qty_purchased',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Quantidade já colocada no carrinho / recebida no ponto de venda.', max_digits=14, verbose_name='Qtd. Adquirida'),
        ),
    ]
