# Generated by Django 5.2.11 on 2026-03-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_qty_purchased_to_purchase_list_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementline',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentagem de desconto copiada da linha de venda/compra (0–100).', max_digits=5, verbose_name='Desconto (%)'),
        ),
    ]
