# Generated by Django 5.2.11 on 2026-03-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_add_discount_pct_to_stockmovementline'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='global_discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto aplicado ao valor total antes do IVA.', max_digits=5, verbose_name='Desconto Global (%)'),
        ),
    ]
