# Generated by Django 5.2.11 on 2026-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_global_discount_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_manufactured',
            field=models.BooleanField(default=False, help_text='Indica que este produto é produzido internamente a partir de uma Receita (BOM).', verbose_name='Produto de Fabrico (BOM)'),
        ),
    ]
