# Generated by Django 5.2.11 on 2026-02-11 20:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Ex: New, Qualified, Proposition, Won', max_length=100, verbose_name='Nome do Estágio')),
                ('sequence', models.IntegerField(default=10, help_text='Ordem de exibição no pipeline (menor = primeiro)', verbose_name='Ordem')),
                ('is_won_stage', models.BooleanField(default=False, help_text='Marca este estágio como ganho/venda concluída', verbose_name='Estágio de Vitória')),
                ('fold_by_default', models.BooleanField(default=False, help_text='Se deve aparecer colapsado no kanban', verbose_name='Colapsado por Padrão')),
                ('routing_in_days', models.IntegerField(default=0, help_text='Dias sem update para highlight (0=desativado). Usado para progress bar colorido.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dias de Roteamento')),
                ('color', models.CharField(default='#6c757d', help_text='Cor hexadecimal (ex: #28a745 para verde)', max_length=7, verbose_name='Cor')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL=global/shared, com valor=privado da empresa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_stages', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Estágio CRM',
                'verbose_name_plural': 'Estágios CRM',
                'ordering': ['sequence', 'name'],
                'unique_together': {('name', 'owner_company')},
            },
        ),
    ]
