# Generated by Django 5.2.11 on 2026-02-12 17:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_associated_contacts'),
        ('core', '0003_company'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255, verbose_name='Opportunity Title')),
                ('description', models.TextField(blank=True, verbose_name='Detailed Description')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Expected Revenue')),
                ('probability', models.IntegerField(default=10, help_text='Probability of closing (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Probability (%)')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10, verbose_name='Priority')),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('COLD_CALL', 'Cold Call'), ('SOCIAL_MEDIA', 'Social Media'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Source')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Expected Close Date')),
                ('lost_reason', models.TextField(blank=True, help_text='Required if stage is Lost', null=True, verbose_name='Lost Reason')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tag system same as Contacts (list of dicts with name+color)', verbose_name='Tags')),
                ('stage_updated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when stage was last changed (for routing calculation)', verbose_name='Stage Updated At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='contacts.contact', verbose_name='Contact')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL=global, with value=private to company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.company', verbose_name='Owner Company')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.crmstage', verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
