# Generated by Django 5.2.11 on 2026-02-12 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company'),
        ('crm', '0002_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity_type', models.CharField(choices=[('TODO', 'To-Do'), ('EMAIL', 'Email'), ('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('DOCUMENT', 'Document'), ('SIGNATURE', 'Signature')], max_length=20, verbose_name='Activity Type')),
                ('summary', models.CharField(max_length=255, verbose_name='Summary')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is Done')),
                ('done_date', models.DateTimeField(blank=True, help_text='Timestamp when activity was marked as done', null=True, verbose_name='Done Date')),
                ('feedback', models.TextField(blank=True, help_text='Note when marking as done (required)', null=True, verbose_name='Feedback')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead', verbose_name='Lead')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL=global, with value=private to company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.company', verbose_name='Owner Company')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
