# Generated by Django 5.2.11 on 2026-02-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='feedback',
            field=models.TextField(blank=True, default='', help_text='Note when marking as done (required)', verbose_name='Feedback'),
        ),
    ]
