# Generated by Django 5.2.11 on 2026-02-12 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_associated_contacts'),
        ('crm', '0004_alter_activity_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='contacts.contact', verbose_name='Contact'),
        ),
    ]
