# Generated by Django 5.2.11 on 2026-02-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_make_lead_contact_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmstage',
            name='is_lost_stage',
            field=models.BooleanField(default=False, help_text='Marca este estágio como perdido/oportunidade falhada', verbose_name='Estágio de Perda'),
        ),
    ]
