# Generated by Django 5.2.11 on 2026-02-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_is_lost_stage_to_crmstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Nome do contacto (preenchido automaticamente se selecionar contacto)', max_length=255, verbose_name='Contact Name'),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_from',
            field=models.EmailField(blank=True, help_text='Email do contacto da oportunidade', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone do contacto da oportunidade', max_length=50, verbose_name='Phone'),
        ),
    ]
