# Generated by Django 5.2.11 on 2026-02-14 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatteractivity_chattermessage'),
        ('crm', '0007_add_contact_fields_to_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='tags',
        ),
        migrations.CreateModel(
            name='CRMTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag Name')),
                ('color', models.CharField(default='#dbc693', max_length=7, verbose_name='Tag Color')),
                ('owner_company', models.ForeignKey(blank=True, help_text='Leave empty for global tags. Set to make tag private to specific company.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_tags', to='core.company', verbose_name='Owner Company')),
            ],
            options={
                'verbose_name': 'CRM Tag',
                'verbose_name_plural': 'CRM Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='crm.crmtag', verbose_name='Tags'),
        ),
    ]
