# Generated by Django 5.2.11 on 2026-02-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_lead_tags_crmtag_lead_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, help_text='Rich text notes (HTML formatted)', verbose_name='Notes'),
        ),
    ]
