# Generated by Django 5.2.11 on 2026-02-16 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Expected Revenue'),
        ),
    ]
