# Generated by Django 5.2.11 on 2026-02-19 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_planned_activity'),
        ('crm', '0010_allow_blank_estimated_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='scheduled_activity',
            field=models.ForeignKey(blank=True, help_text='Blueprint que originou esta atividade (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to='core.scheduledactivity', verbose_name='Atividade Programada'),
        ),
    ]
