# Generated by Django 5.2.11 on 2026-02-19 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_add_scheduled_activity_to_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatter_notes', to='crm.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Nota do Lead',
                'verbose_name_plural': 'Notas do Lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
