# Generated by Django 5.2.11 on 2026-02-19 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_lead_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('outbound', 'Enviado'), ('inbound', 'Recebido')], default='outbound', max_length=8, verbose_name='Direção')),
                ('from_email', models.EmailField(max_length=254, verbose_name='De')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Para')),
                ('subject', models.CharField(max_length=998, verbose_name='Assunto')),
                ('body', models.TextField(verbose_name='Corpo')),
                ('message_id', models.CharField(blank=True, help_text='Header Message-ID do email enviado. Usado para fazer match de respostas.', max_length=998, verbose_name='Message-ID')),
                ('in_reply_to', models.CharField(blank=True, help_text='Header In-Reply-To do email recebido.', max_length=998, verbose_name='In-Reply-To')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm.lead', verbose_name='Lead')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Nulo para emails recebidos (inbound).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_lead_emails', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Email do Lead',
                'verbose_name_plural': 'Emails do Lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
