# Generated by Django 5.2.11 on 2026-02-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_add_lead_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadEmail',
        ),
    ]
