# Generated by Django 5.2.11 on 2026-02-22 19:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_company_language'),
        ('crm', '0014_delete_leademail'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmstage',
            name='win_probability',
            field=models.FloatField(default=10.0, help_text='Calculado automaticamente: % de leads ganhas que passaram por este estágio', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Probabilidade Histórica (%)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_prospect',
            field=models.BooleanField(default=False, help_text='Prospecto ainda não qualificado — não aparece no pipeline principal', verbose_name='É Prospecto'),
        ),
        migrations.AddField(
            model_name='lead',
            name='probability_locked',
            field=models.BooleanField(default=False, help_text='Se True, a probabilidade não é atualizada automaticamente pelo sistema', verbose_name='Probabilidade Manual'),
        ),
        migrations.CreateModel(
            name='CRMConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('predictive_scoring', models.BooleanField(default=True, help_text='Calcula automaticamente a probabilidade de fecho com base no histórico de leads', verbose_name='Pontuação Preditiva')),
                ('prospects_enabled', models.BooleanField(default=False, help_text='Ativa a fase de prospecto antes do pipeline (leads não qualificadas)', verbose_name='Prospectos')),
                ('lead_generation_years', models.IntegerField(default=3, help_text='Quantos anos de histórico usar para gerar leads automáticas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Período Histórico (anos)')),
                ('last_probability_update', models.DateTimeField(blank=True, null=True, verbose_name='Última Atualização de Probabilidades')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_config', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configurações CRM',
                'verbose_name_plural': 'Configurações CRM',
            },
        ),
    ]
