# Generated by Django 5.2.11 on 2026-02-22 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_add_prospect_probability_crmconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que a lead foi ganha ou perdida. Preenchido automaticamente.', null=True, verbose_name='Data de Fecho'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason_category',
            field=models.CharField(blank=True, choices=[('PRICE', 'Preço'), ('COMPETITOR', 'Concorrência'), ('TIMING', 'Timing / Sem urgência'), ('NO_BUDGET', 'Sem Orçamento'), ('NO_RESPONSE', 'Sem Resposta'), ('REQUIREMENTS', 'Requisitos não cumpridos'), ('OTHER', 'Outro')], default='', help_text='Categoria estruturada do motivo de perda (para análise em relatórios)', max_length=20, verbose_name='Categoria do Motivo de Perda'),
        ),
        migrations.AlterField(
            model_name='crmconfig',
            name='lead_generation_years',
            field=models.IntegerField(default=3, help_text='Quantos anos de histórico usar para gerar leads automáticas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Período Histórico (anos)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('COLD_CALL', 'Cold Call'), ('SOCIAL_MEDIA', 'Social Media'), ('RETURNING', 'Cliente Recorrente'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Source'),
        ),
    ]
