# Generated by Django 5.2.11 on 2026-03-24 22:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_document_sequence'),
        ('inventory', '0018_add_global_discount_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qty_produced', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Quantidade do produto final produzida por uma execução desta receita. Ex: 12 fatias.', max_digits=12, verbose_name='Quantidade Produzida')),
                ('labor_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Custo de mão-de-obra por execução completa desta receita (não por unidade).', max_digits=10, verbose_name='Custo de Mão-de-obra (€)')),
                ('notes', models.TextField(blank=True, default='', help_text='Instruções de preparação, anotações, etc.', verbose_name='Notas')),
                ('owner_company', models.ForeignKey(blank=True, help_text='NULL = global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='core.company', verbose_name='Empresa')),
                ('product', models.OneToOneField(help_text='Produto acabado que esta receita produz.', on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='inventory.product', verbose_name='Produto')),
                ('uom', models.ForeignKey(help_text='Unidade de medida do produto final. Ex: Fatia, Unidade, kg.', on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='inventory.uom', verbose_name='UdM do Produto')),
            ],
            options={
                'verbose_name': 'Receita (BOM)',
                'verbose_name_plural': 'Receitas (BOM)',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBOMLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantidade deste componente necessária para produzir qty_produced do produto final.', max_digits=12, verbose_name='Quantidade')),
                ('sequence', models.PositiveSmallIntegerField(default=10, help_text='Ordem de apresentação na receita.', verbose_name='Ordem')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notas')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bom.productbom', verbose_name='Receita')),
                ('component', models.ForeignKey(help_text='Ingrediente ou sub-produto que compõe esta receita.', on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='inventory.product', verbose_name='Componente')),
                ('uom', models.ForeignKey(help_text='Unidade em que a quantidade é expressa nesta linha.', on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='inventory.uom', verbose_name='UdM')),
            ],
            options={
                'verbose_name': 'Linha de Receita',
                'verbose_name_plural': 'Linhas de Receita',
                'ordering': ['sequence', 'component__name'],
            },
        ),
    ]
