# Generated by Django 5.2.11 on 2026-03-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
        ('core', '0029_document_sequence'),
        ('inventory', '0018_add_global_discount_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbom',
            name='internal_reference',
            field=models.CharField(blank=True, default='', help_text='Código único desta receita (ex: BOM-001).', max_length=64, verbose_name='Referência Interna'),
        ),
        migrations.AddConstraint(
            model_name='productbom',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_reference__gt', '')), fields=('internal_reference', 'owner_company'), name='unique_bom_internal_ref_per_company'),
        ),
    ]
