# Generated by Django 5.2.11 on 2026-03-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='origin',
            field=models.CharField(blank=True, default='', help_text='Referência externa (ex: SO/2026/00001).', max_length=64, verbose_name='Origem'),
        ),
    ]
