# Generated by Django 5.2.11 on 2026-03-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_payment_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentterm',
            options={'ordering': ['-is_default', 'days', 'name'], 'verbose_name': 'Condição de Pagamento', 'verbose_name_plural': 'Condições de Pagamento'},
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Seleccionada automaticamente em novas encomendas de compra.', verbose_name='Padrão'),
        ),
    ]
