# Generated by Django 5.2.11 on 2026-03-05 00:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_paymentterm_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentagem de desconto aplicada ao preço unitário (0–100).', max_digits=5, verbose_name='Desconto (%)'),
        ),
    ]
